<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>raf</ToolCommandName>
        
        <PackageId>raf</PackageId>
        <Version>1.0.0</Version>
        <Authors>Rafael Pigatto</Authors>
        <Description>Raf like Git implementation in C#</Description>

        <PackageType>DotnetTool</PackageType>
        <PackageOutputPath>./nupkg</PackageOutputPath>
        
    </PropertyGroup>

</Project>